language: ruby
rvm:
  - 2.0.0
services:
  - redis-server
before_script:
  - cp config/settings.yml.travis config/settings.yml
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
addons:
  postgresql: "9.3"
git:
  submodules: false
