language: ruby
rvm:
  - 2.5.1
services:
  - redis-server
before_install:
  - git submodule update --init common-gems
before_script:
  - cp config/settings.yml.travis config/settings.yml
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
addons:
  postgresql: "10"
git:
  submodules: false
sudo: false
cache: bundler
