---
- hosts: all
  gather_facts: no
  roles:
    - deploy_setup
  tasks:

    - name: create folders
      sudo: yes
      file:
        path: "{{ deploy_setup_dir }}/{{ item }}"
        owner: "{{ provision_user }}"
        state: directory
      with_items: deploy_setup_folders
      when: inventory_hostname == "worker01"

    - name: check out projects
      sudo: yes
      git:
        repo: "{{ item.repo }}"
        dest: "{{ deploy_setup_dir }}/files/projects/{{ item.name }}"
        update: no
      with_items: deploy_setup_projects
      when: inventory_hostname == "worker01"
